name: Build Hexo & Deploy Pages
on:
  push:
    branches: [ main ]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: Node 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: 安装依赖
        run: npm install --no-audit --no-fund

      - name: 构建静态站点
        run: |
          npx hexo clean
          npx hexo generate
          # 不存在public就自动创建空文件夹兜底
          mkdir -p public

      - name: 部署页面
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
